### ISSUE TITLE
Opening a stream with a framesPerBuffer of 0 causes a buffer underrun and a stutter

### ISSUE THREAD

**Issue by Darfk** [gordonklaus/portaudio#40]
https://github.com/gordonklaus/portaudio/blob/bb74aa48564155f02aa5a6dc1e833eceaca86a8c/examples/stereoSine.go#L30

I noticed in your example I receive many messages about a underrun accompanied with a jarring stutter, I simply changed the `framesPerBuffer` parameter to `1024` and no longer received these messages.

Terminal output with original `framesPerBuffer` amount:

```
% go run main.go
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
```

**Comment by gordonklaus** [comment]
I'm not sure what the real issue here is.  Passing zero as `framesPerBuffer` is valid (although it would be more explicit to pass [FramesPerBufferUnspecified](https://github.com/gordonklaus/portaudio/blob/bb74aa48564155f02aa5a6dc1e833eceaca86a8c/portaudio.go#L389)).

I assume PortAudio (or ALSA) would then choose a buffer size appropriate to achieve the desired latency.  Perhaps your latency settings are unreasonably low?  I'm not familiar with how to configure ALSA.

Sorry I can't be of more help.  I recommend asking on [the mailing list](http://www.portaudio.com/contacts.html).
